# Generated by Django 6.0.2 on 2026-02-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Image originale')),
                ('meme_image', models.ImageField(upload_to='memes/%Y/%m/%d/', verbose_name='Mème généré')),
                ('top_text', models.CharField(blank=True, max_length=200, verbose_name='Texte du haut')),
                ('bottom_text', models.CharField(blank=True, max_length=200, verbose_name='Texte du bas')),
                ('font_name', models.CharField(default='Impact', max_length=60, verbose_name='Police')),
                ('font_size_top', models.PositiveSmallIntegerField(default=42, verbose_name='Taille texte haut')),
                ('font_size_bot', models.PositiveSmallIntegerField(default=42, verbose_name='Taille texte bas')),
                ('color_top', models.CharField(default='#ffffff', max_length=7, verbose_name='Couleur texte haut')),
                ('color_bottom', models.CharField(default='#ffffff', max_length=7, verbose_name='Couleur texte bas')),
                ('stroke_color_top', models.CharField(default='#000000', max_length=7, verbose_name='Couleur contour haut')),
                ('stroke_color_bot', models.CharField(default='#000000', max_length=7, verbose_name='Couleur contour bas')),
                ('stroke_width', models.PositiveSmallIntegerField(default=3, verbose_name='Épaisseur contour')),
                ('is_bold', models.BooleanField(default=True, verbose_name='Gras')),
                ('is_italic', models.BooleanField(default=False, verbose_name='Italique')),
                ('is_uppercase', models.BooleanField(default=True, verbose_name='Majuscules')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Clé de session')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Taille fichier (octets)')),
            ],
            options={
                'verbose_name': 'Mème',
                'verbose_name_plural': 'Mèmes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('image', models.ImageField(upload_to='templates/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template de mème',
                'verbose_name_plural': 'Templates de mèmes',
                'ordering': ['name'],
            },
        ),
    ]
